site_name: Python-Bitflow
repo_url: https://github.com/bitflow-stream/python-bitflow
site_author: mwallschlaeger
site_description: Python Bitflow Documentation
theme: readthedocs
plugins:
    - search
markdown_extensions:
    - sane_lists
    - smarty
    - toc:
        permalink: True
nav:
    - Home:
        - The Bitflow Project: "https://bitflow.readthedocs.io/en/latest/"
        - Data Sources, Sinks and Format: "https://bitflow.readthedocs.io/en/latest/data-format/"
        - Bitflow Script: "https://bitflow.readthedocs.io/projects/bitflow-antlr-grammars/en/latest/bitflow-script/"
    - Implementations:
        - go-bitflow: "https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/"
        - bitflow4j (Github): "https://github.com/bitflow-stream/bitflow4j"
        - python-bitflow: "index.md"
    - Related Projects:
        - bitflow-collector: "https://bitflow.readthedocs.io/projects/go-bitflow-collector/en/latest/"
        - bitflow-coordinator (Github): "https://github.com/bitflow-stream/bitflow-coordinator"
        - bitflow-process-agent (Github): "https://github.com/bitflow-stream/bitflow-process-agent"

